version: '3.8'

services:

  db:
    image: postgres:13
    container_name: workshop-db
    environment:
      POSTGRES_USER: workshops_user
      POSTGRES_PASSWORD: oc2024
      POSTGRES_DB: workshopsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workshops_user -d workshopsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: workshop-app
    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/workshopsdb
      SPRING_DATASOURCE_USERNAME: workshops_user
      SPRING_DATASOURCE_PASSWORD: oc2024

    ports:
      - "8080:8080"

volumes:
  postgres_data: